version: '3.8'

services:
  app:
    image: node:18
    command: yarn run start
    working_dir: /workspace
    volumes:
      - .:/workspace
    logging:
      options:
        max-size: 50k
        max-file: '1'
    restart: 'no'
